name: Deploy infrastructure
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-west-2
    steps:
      - uses: actions/checkout@v3
      - name: Setup src bucket
        run:  |
          sh setup_src_bucket.sh
      - name: build and upload src
        run:  |
          sh upload-src.sh
      - name: run terraform
        run:  |
          cd infrastructure
          sh setup_terraform_bucket.sh
          terraform init
          terraform apply -auto-approve
