name: Deploy infrastructure
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup src bucket
        run:  |
          sh setup_src_bucket.sh

